In [1]:
# Import necessary libraries
import numpy as np

In [2]:

#Adaline neural network
def Adaline(Input, Target, lr=0.2, stop=0.001):
    weight = np.random.random(Input.shape[1])
    bias   = np.random.random(1)
    
    Error=[stop +1]
    # check the stop condition for the network
    while Error[-1] > stop or Error[-1]-Error[-2] > 0.0001:
        error = []
        for i in range(Input.shape[0]):
            Y_input = sum(weight*Input[i]) + bias
             
            # Update the weight
            for j in range(Input.shape[1]):
                weight[j]=weight[j] + lr*(Target[i]-Y_input)*Input[i][j]
 
            # Update the bias
            bias=bias + lr*(Target[i]-Y_input)
             
            # Store squared error value
            error.append((Target[i]-Y_input)**2)
        # Store sum of square errors
        Error.append(sum(error))
        print('Error :',Error[-1])
    return weight, bias
 
# Input dataset
x = np.array([[1.0, 1.0, 1.0],
              [1.0, -1.0, 1.0],
              [-1.0, 1.0, 1.0],
              [-1.0, -1.0, -1.0]])
# Target values
t = np.array([1, 1, 1, -1])
 
w,b = Adaline(x, t, lr=0.2, stop=0.001)
print('weight :',w)
print('Bias :',b)

Error : [2.43608438]
Error : [1.78307939]
Error : [1.24122122]
Error : [0.85932903]
Error : [0.59474324]
Error : [0.41161523]
Error : [0.28487404]
Error : [0.19715795]
Error : [0.13645068]
Error : [0.0944359]
Error : [0.06535797]
Error : [0.04523348]
Error : [0.03130555]
Error : [0.0216662]
Error : [0.01499492]
Error : [0.01037781]
Error : [0.00718236]
Error : [0.00497082]
Error : [0.00344025]
Error : [0.00238096]
Error : [0.00164783]
Error : [0.00114044]
Error : [0.00078929]
weight : [0.00972713 0.00972713 0.98808675]
Bias : [0.00972713]


In [3]:
# Predict from the evaluated weight and bias of adaline
def prediction(X,w,b):
    y=[]
    for i in range(X.shape[0]):
        x = X[i]
        y.append(sum(w*x)+b)
    return y
prediction(x,w,b)

[array([1.01726813]),
 array([0.99781388]),
 array([0.99781388]),
 array([-0.99781388])]